version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: Europe/Warsaw
    labels: [dependencies]
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: Europe/Warsaw
    labels: [dependencies, ci]
    open-pull-requests-limit: 5
